/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import classesbasicas.Funcionario;
import ConexaoDB.DadosFuncionario;
import javax.swing.JOptionPane;
import validacaodecampos.SomenteLetras;
import validacaodecampos.SomenteNumeros;

/**
 *
 * @author Natália
 */
public class FormCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastroFuncionario
     */
    public FormCadastroFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtBairroFun.setDocument(new SomenteLetras());
        txtCepFun.setDocument(new SomenteNumeros());
        txtCidadeFun.setDocument(new SomenteLetras());
        txtCpfFun.setDocument(new SomenteNumeros());
        //txtEmailFun
        txtEstadoFun.setDocument(new SomenteLetras());
        txtLogradouroFun.setDocument(new SomenteLetras());
        txtNomeFun.setDocument(new SomenteLetras());
        txtNumeroFun.setDocument(new SomenteNumeros());
        txtTelefoneFun.setDocument(new SomenteNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpfFun = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBairroFun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLogradouroFun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroFun = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCidadeFun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEstadoFun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCepFun = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefoneFun = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmailFun = new javax.swing.JTextField();
        jButtonFuncionarioFormCad = new javax.swing.JButton();
        jLabelEmailFun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");
        jLabel1.setToolTipText("");

        txtNomeFun.setToolTipText("");
        txtNomeFun.setName(""); // NOI18N
        txtNomeFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFunActionPerformed(evt);
            }
        });

        jLabel2.setText("Cpf:");
        jLabel2.setToolTipText("");

        txtCpfFun.setToolTipText("");
        txtCpfFun.setName(""); // NOI18N
        txtCpfFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfFunActionPerformed(evt);
            }
        });

        jLabel10.setText("Bairro:");
        jLabel10.setToolTipText("");

        txtBairroFun.setToolTipText("");
        txtBairroFun.setName(""); // NOI18N
        txtBairroFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroFunActionPerformed(evt);
            }
        });

        jLabel3.setText("Logradouro:");
        jLabel3.setToolTipText("");

        txtLogradouroFun.setToolTipText("");
        txtLogradouroFun.setName(""); // NOI18N
        txtLogradouroFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogradouroFunActionPerformed(evt);
            }
        });

        jLabel4.setText("Numero:");
        jLabel4.setToolTipText("");

        txtNumeroFun.setToolTipText("");
        txtNumeroFun.setName(""); // NOI18N
        txtNumeroFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroFunActionPerformed(evt);
            }
        });

        jLabel6.setText("Cidade:");
        jLabel6.setToolTipText("");

        txtCidadeFun.setToolTipText("");
        txtCidadeFun.setName(""); // NOI18N
        txtCidadeFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeFunActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");
        jLabel5.setToolTipText("");

        txtEstadoFun.setToolTipText("");
        txtEstadoFun.setName(""); // NOI18N
        txtEstadoFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoFunActionPerformed(evt);
            }
        });

        jLabel7.setText("CEP:");
        jLabel7.setToolTipText("");

        txtCepFun.setToolTipText("");
        txtCepFun.setName(""); // NOI18N
        txtCepFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepFunActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefone:");
        jLabel8.setToolTipText("");

        txtTelefoneFun.setToolTipText("");
        txtTelefoneFun.setName(""); // NOI18N
        txtTelefoneFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneFunActionPerformed(evt);
            }
        });

        jLabel9.setText("Email:");
        jLabel9.setToolTipText("");

        txtEmailFun.setToolTipText("");
        txtEmailFun.setName(""); // NOI18N
        txtEmailFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFunFocusLost(evt);
            }
        });
        txtEmailFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFunActionPerformed(evt);
            }
        });

        jButtonFuncionarioFormCad.setText("cadastrar");
        jButtonFuncionarioFormCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarioFormCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogradouroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNomeFun)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCpfFun, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(txtBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(135, 135, 135)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCepFun, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButtonFuncionarioFormCad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(txtCpfFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addComponent(txtBairroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFuncionarioFormCad)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFunActionPerformed

    private void txtCpfFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfFunActionPerformed

    private void txtBairroFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroFunActionPerformed

    private void txtLogradouroFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogradouroFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogradouroFunActionPerformed

    private void txtNumeroFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroFunActionPerformed

    private void txtCidadeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeFunActionPerformed

    private void txtEstadoFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoFunActionPerformed

    private void txtCepFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepFunActionPerformed

    private void txtTelefoneFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFunActionPerformed

    private void txtEmailFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFunActionPerformed

    private void jButtonFuncionarioFormCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioFormCadActionPerformed
        // TODO add your handling code here:
        try {
            Funcionario fun = new Funcionario();
            
            fun.setCpf(txtCpfFun.getText());
            fun.setNome(txtNomeFun.getText());
            fun.setLogradouro(txtLogradouroFun.getText());
            fun.setNumero(Integer.parseInt(txtNumeroFun.getText()));
            fun.setBairro(txtBairroFun.getText());
            fun.setCidade(txtCidadeFun.getText());
            fun.setEstado(txtEstadoFun.getText());
            fun.setCep(Integer.parseInt(txtCepFun.getText()));
            fun.setEmail(txtEmailFun.getText());
            fun.setTelefone(Integer.parseInt(txtTelefoneFun.getText()));
            
            DadosFuncionario df = new DadosFuncionario();
            df.cadastrarF(fun);
            
            JOptionPane.showMessageDialog(rootPane, "Funcionario cadastrado com sucesso.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_jButtonFuncionarioFormCadActionPerformed

    private void txtEmailFunFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFunFocusLost
        // TODO add your handling code here:
        if ((txtEmailFun.getText().contains("@"))
                && (txtEmailFun.getText().contains("."))
                && (!txtEmailFun.getText().contains(" "))) {

            String usuario = new String(txtEmailFun.getText().substring(0,
                    txtEmailFun.getText().lastIndexOf('@')));

            String dominio = new String(txtEmailFun.getText().substring(txtEmailFun.getText().lastIndexOf('@') + 1, txtEmailFun.getText().length()));

            if ((usuario.length() >= 1) && (!usuario.contains("@"))
                    && (dominio.contains(".")) && (!dominio.contains("@")) && (dominio.indexOf(".")
                    >= 1) && (dominio.lastIndexOf(".") < dominio.length() - 1)) {

                jLabelEmailFun.setText("");
                jButtonFuncionarioFormCad.setEnabled(true);

            } else {
                jButtonFuncionarioFormCad.setEnabled(false);

                jLabelEmailFun.setText("E-mail Inválido");

                txtEmailFun.requestFocus();

            }

        } else {
            jButtonFuncionarioFormCad.setEnabled(false);

            jLabelEmailFun.setText("E-mail Inválido");

            txtEmailFun.requestFocus();

        }
    }//GEN-LAST:event_txtEmailFunFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFuncionarioFormCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEmailFun;
    private javax.swing.JTextField txtBairroFun;
    private javax.swing.JTextField txtCepFun;
    private javax.swing.JTextField txtCidadeFun;
    private javax.swing.JTextField txtCpfFun;
    private javax.swing.JTextField txtEmailFun;
    private javax.swing.JTextField txtEstadoFun;
    private javax.swing.JTextField txtLogradouroFun;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JTextField txtNumeroFun;
    private javax.swing.JTextField txtTelefoneFun;
    // End of variables declaration//GEN-END:variables
}
